name: train_test_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.2
  - pandas=2.2.2
  - boto3=1.34.154
  - scikit-learn=1.5.1
  - pyyaml=6.0.1
  - mlflow=2.12.2
  - matplotlib=3.8.4
  - numpy=1.26.4
  - seaborn=0.13.2
  - xgboost=2.1.1