name: data_role_advisor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - mlflow=2.16.2
  - fastapi=0.112.2
  - uvicorn=0.20.0
  - boto3=1.34.69
  - pandas=2.2.2
  - xgboost=2.1.1
  - pydantic=2.8.2