name: Cypress Docker Push
on: 
  workflow_run:
    workflows: ['App test']
    types:
      - completed

jobs:
    - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Test Services with Docker Compose
      run: |
        docker compose up --build --detach
        docker compose ps
        docker images 
        echo "Verificando imagens específicas:"
        docker images data_role_advisor-train
        docker images data_role_advisor-infer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Push Train Image
        run: docker push vitorabdo/data-role-advisor:latest

    - name: Push Infer Image
      run: docker push vitorabdo/data-role-advisor:latest