name: Workflow 2

on:
  workflow_run:
    workflows: ["App test"]
    types:
      - completed

jobs:
  dependent-job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run your steps
        run: echo "Running workflow 2 after Workflow 1 succeeded"
